# Generated by Django 4.0.1 on 2022-01-07 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('theory', '0006_auto_20210331_1837'),
        ('practice', '0008_auto_20210331_1837'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='сообщение')),
                ('type', models.CharField(choices=[('message', 'Message'), ('article_reply', 'Article Reply'), ('exercise_reply', 'Exercise Reply')], default='message', max_length=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='theory.article', verbose_name='Статья')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='practice.exercise', verbose_name='Упражнение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
                'ordering': ('created_at',),
            },
        ),
    ]
