# Generated by Django 4.0.1 on 2022-01-28 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theory', '0006_auto_20210331_1837'),
        ('practice', '0008_auto_20210331_1837'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='theory.article', verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='message',
            name='exercise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='practice.exercise', verbose_name='Упражнение'),
        ),
    ]
