# Generated by Django 4.0.1 on 2022-01-29 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_article_alter_message_exercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(default='message', max_length=14),
        ),
    ]
