# Generated by Django 4.0.1 on 2022-01-29 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_message_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='type',
            new_name='message_type',
        ),
    ]
