# Generated by Django 4.0.1 on 2022-01-29 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_rename_type_message_message_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='message_type',
        ),
        migrations.AddField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('message', 'Message'), ('article_reply', 'Article Reply'), ('exercise_reply', 'Exercise Reply')], default='message', max_length=14),
        ),
    ]
