# Generated by Django 3.1.7 on 2021-03-30 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theory', '0004_auto_20210324_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.CharField(max_length=100000, verbose_name='содержание'),
        ),
    ]
