# Generated by Django 3.1.7 on 2021-03-31 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theory', '0005_auto_20210330_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=models.CharField(blank=True, max_length=20000, verbose_name='описание'),
        ),
    ]
