# Generated by Django 3.1.7 on 2021-03-23 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theory', '0002_auto_20210322_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
