repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      args:
        - -S
      language_version: python3.8
-   repo: https://gitlab.com/pycqa/flake8
    rev: stable
    hooks:
    - id: flake8

