repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v2.5.0"
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
  - repo: git@github.com:pre-commit/mirrors-yapf.git
    rev: v0.26.0
    hooks:
      - id: yapf
        args: [ '--style=.style.yapf', '--parallel', '--in-place', '-ir', 'app/' ]
  - repo: https://gitlab.com/pycqa/flake8
    rev: '3.8.4'
    hooks:
      - id: flake8
        args: ['--config=.flake8']
