version: "3"

services:
  web_app:
    command: ./wait-for-it/wait-for-it.sh postgres:$POSTGRES_PORT -- pipenv run dev
    build:
      context: ./
      dockerfile: Dockerfile
      target: base
    env_file:
      - .env
    restart: on-failure
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - ./:/usr/src/app/
      - /usr/src/app/wait-for-it/
  postgres:
    image: postgres
    restart: on-failure
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
  redis:
    image: redis:alpine
    ports:
      - ${REDIS_PORT}:6379
