# Generated by Django 3.1.7 on 2021-03-22 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theory', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TheoryArticle',
            new_name='Article',
        ),
        migrations.RenameModel(
            old_name='TheoryTopic',
            new_name='Topic',
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'Тема', 'verbose_name_plural': 'Темы'},
        ),
    ]
