# Generated by Django 3.1.7 on 2021-03-22 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'verbose_name': 'Задание', 'verbose_name_plural': 'Задания'},
        ),
        migrations.AlterField(
            model_name='exercise',
            name='correct_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='practice.exerciseansweroption'),
        ),
        migrations.AlterField(
            model_name='exercisereport',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='practice.exerciseansweroption'),
        ),
        migrations.AlterField(
            model_name='exercisereport',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='practice.exercise'),
        ),
    ]
