# Generated by Django 3.1.7 on 2021-03-23 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theory', '0003_topic_description'),
        ('practice', '0002_auto_20210322_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='theory.topic'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exerciseansweroption',
            name='exercise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='practice.exercise'),
            preserve_default=False,
        ),
    ]
