# Generated by Django 3.1.7 on 2021-03-24 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theory', '0003_topic_description'),
        ('practice', '0003_auto_20210323_1308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exerciseansweroption',
            options={'verbose_name': 'Ответ на задание', 'verbose_name_plural': 'Ответы на задание'},
        ),
        migrations.AlterField(
            model_name='exercise',
            name='correct_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correct_exercises', to='practice.exerciseansweroption'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='theory.topic'),
        ),
    ]
