# Generated by Django 3.1.7 on 2021-03-24 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theory', '0004_auto_20210324_2228'),
        ('practice', '0004_auto_20210324_0045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'verbose_name': 'задание', 'verbose_name_plural': 'задания'},
        ),
        migrations.AlterModelOptions(
            name='exerciseansweroption',
            options={'verbose_name': 'ответ на задание', 'verbose_name_plural': 'ответы на задание'},
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='correct_option',
        ),
        migrations.AddField(
            model_name='exerciseansweroption',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='правильный ответ'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.CharField(max_length=4000, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='title',
            field=models.CharField(max_length=200, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='theory.topic', verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='exerciseansweroption',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice.exercise', verbose_name='задание'),
        ),
        migrations.AlterField(
            model_name='exerciseansweroption',
            name='option',
            field=models.CharField(max_length=200, verbose_name='ответ'),
        ),
        migrations.AlterField(
            model_name='exercisereport',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='practice.exerciseansweroption', verbose_name='ответ'),
        ),
        migrations.AlterField(
            model_name='exercisereport',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='practice.exercise', verbose_name='задание'),
        ),
    ]
